spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: itoken-zuul
      label: master
      profile: dev
  main:
    allow-bean-definition-overriding: true
    # 当bean重复定义时允许相同key情况下beanDefinition实例的覆盖